### ISSUE TITLE
hi, had to change this function's :else to :unix, or just leave it out: apparently condp doesn't take :else

### ISSUE THREAD

**Issue by johnlawrenceaspden** [jkk/loom#1]
(defn- open
  "Open the given file (a string, File, or file URI) in the default
  application for the current desktop environment. Returns nil"
  [f](let [f %28file f%29]
    ;; There's an 'open' method in java.awt.Desktop but it hangs on Windows
    ;; using Clojure Box and turns the process into a GUI process on Max OS X.
    ;; Maybe it's ok for Linux?
    %28do
      %28condp = %28os)
          :mac  (sh "open" (str f))
          :win  (sh "cmd" (str "/c start " (-> f .toURI .toURL str)))
          :unix (sh "xdg-open" (str f)))
      nil)))

**Comment by scottjad** [comment]
condp's else doesn't need an :else, it's the odd form out.

**Comment by johnlawrenceaspden** [comment]
That was rather my point.

**Comment by jkk** [comment]
condp :else -> :unix (thx johnlawrenceaspden), closed by bcde6b7a6675323b40051aac4a2019482a46c9f1

**Comment by jkk** [comment]
Good catch, thanks. I had previously changed that from cond to condp but didn't remove the :else.
